name: ⛔ Documentation & Examples
description: Issues with the Documentation and/or the Examples
labels: docs

body:
  - type: markdown
    attributes:
      value: |
        We have our own dedicated repository for the examples. Please open your
        documentation-related issue at https://github.com/wenzhixin/bootstrap-table-examples
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of your support question.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Love bootstrap-table? Please consider supporting our collective:
        👉  https://opencollective.com/bootstrap-table/donate